# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: meta
  hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
        # exclude: '^docs/source/reference/generated/.*\.rst'
      - id: fix-byte-order-marker
        # exclude: '^docs/source/reference/generated/.*\.rst'
      - id: no-commit-to-branch
        args: [ --branch, main ]
      - id: trailing-whitespace
        # exclude: '^docs/source/reference/generated/.*\.rst'
- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 24.8.0
  hooks:
    - id: black
      files: '.*\.pyi?$'
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.14.1'
  hooks:
    - id: mypy
      additional_dependencies:
        - "pydantic>=2.0.0"
