
name: TestSuite

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    name: Run linters with pre-commit
    runs-on: ubuntu-latest
    env:
        USERNAME: ${{ secrets.SAILOR_USER }}
        ACCESS_TOKEN: ${{ secrets.MOON_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          git config --global url."https://${USERNAME}:${ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"
          pip install -e '.[dev]'
      - name: Run pre-commit hooks
        run: SKIP=no-commit-to-branch pre-commit run --all-files --show-diff-on-failure

  testing:
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04","ubuntu-latest" ,"macos-13","macos-15", "windows-2022"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    env:
      USERNAME: ${{ secrets.SAILOR_USER }}
      ACCESS_TOKEN: ${{ secrets.MOON_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          git config --global url."https://${USERNAME}:${ACCESS_TOKEN}@github.com/".insteadOf "https://github.com/"
          pip install -e '.[dev]'
        shell: bash
      - name: Run Tests
        run: python -m pytest -v
